osx_image: xcode12.3
language: objective-c

# Handle git submodules yourself
# http://stackoverflow.com/a/24600210/805882
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i -e 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 8 (12" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID

install:
#  - mkdir Submodules/iBurn-Data/data/2016/2016
  - touch iBurn/GoogleService-Info.plist
  - echo -e "<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> <plist version="1.0"> <dict> <key>items</key> <array> <dict> <key>assets</key> <array> <dict> <key>kind</key> <string>software-package</string> <key>url</key> <!-- Change URL bellow to the location of your ipa --> <string>https://LINK-TO-YOUR-FILE-SHARE</string> </dict> </array> <key>metadata</key> <dict> <key>bundle-identifier</key> <!-- change bundle identifer to the one you are using in your app --> <string>com.mallibone.sample</string> <key>bundle-version</key> <!-- change version bellow to the version you are providing --> <string>1.0</string> <key>kind</key> <string>software</string> <key>title</key> <!-- change title to match your app name --> <string>Mobile Friendly</string> </dict> </dict> </array> </dict> </plist>" > iBurn/GoogleService-Info.plist
  - echo -e "#define MAPBOX_ACCESS_TOKEN test\n#define CRASHLYTICS_API_TOKEN test\n" > ./iBurn/InfoPlistSecrets.h
  - echo -e "NSString * const kBRCHockeyBetaIdentifier = @\"\";\nNSString * const kBRCHockeyLiveIdentifier = @\"\";\nNSString * const kBRCEmbargoPasscodeSHA256Hash = @\"\";\nNSString * const kBRCUpdatesURLString = @\"\";\nNSString * const kBRCMapBoxStyleURL = @\"https://example.com\";\nNSString * const kBRCMapBoxAccessToken = @\"\";\n" > ./iBurn/BRCSecrets.m

before_script:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install
script:
  - set -o pipefail
  - xcodebuild -workspace iBurn.xcworkspace -scheme iBurn -sdk iphonesimulator -destination "id=$IOS_SIMULATOR_UDID" build | xcpretty -c
